---

- name: Fedora Build Playbook
  hosts: all
  tasks:
    - name: test connection
      ansible.builtin.command: hostname
      register: output
      changed_when: false
    
    - name: debug output
      debug:
        var: output.stdout_lines

    - name: Run Fedora Build Role
      ansible.builtin.include_role:
        name: fed_apps
